# Generated by Django 3.2.7 on 2021-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField()),
                ('primer_sequence', models.CharField(max_length=200)),
                ('mismatchscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField()),
                ('global_termination_probability', models.FloatField()),
                ('local_termination_probability', models.FloatField()),
                ('chimerism_model', models.CharField(max_length=10)),
                ('chimerism_proportion', models.FloatField()),
            ],
        ),
    ]
