# Generated by Django 3.2.7 on 2021-09-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_remove_sequence_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnealedPrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='primer',
            old_name='mismatchscore',
            new_name='mismatch_score',
        ),
        migrations.AddField(
            model_name='primer',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primer',
            name='primer_sequence',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chimerism_model',
            field=models.CharField(choices=[('A', 'model A'), ('B', 'model B'), ('C', 'model C')], max_length=10),
        ),
        migrations.CreateModel(
            name='PrimerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('chimerism_positions', models.JSONField()),
                ('forward_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_primer', to='simulator.annealedprimer')),
                ('reverse_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_primer', to='simulator.annealedprimer')),
            ],
        ),
        migrations.AddField(
            model_name='annealedprimer',
            name='primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.primer'),
        ),
    ]
