# Generated by Django 3.2.7 on 2021-09-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20210918_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='direction',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='mismatch_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chimerism_model',
            field=models.CharField(blank=True, choices=[('A', 'model A'), ('B', 'model B'), ('C', 'model C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chimerism_proportion',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='global_termination_probability',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='local_termination_probability',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number_of_products',
            field=models.IntegerField(blank=True),
        ),
    ]
