# Generated by Django 3.2.7 on 2021-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_primer_primer_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='chimerism_proportion',
            new_name='chimerism_probability',
        ),
        migrations.AddField(
            model_name='primer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
