# Generated by Django 3.2.7 on 2021-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='primer_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='sequence_file',
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[('seq', 'sequence file'), ('prim', 'primer file')], max_length=20),
        ),
    ]
