# Generated by Django 3.2.7 on 2021-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_auto_20210918_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primer',
            old_name='primer_sequence',
            new_name='sequence',
        ),
        migrations.AddField(
            model_name='sequence',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
