# Generated by Django 3.2.7 on 2021-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_auto_20210919_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.TextField(blank=True),
        ),
    ]
