# Generated by Django 3.2.7 on 2021-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_alter_sequence_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sequence', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
