# Generated by Django 3.2.7 on 2021-09-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_primerinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimerInput',
        ),
    ]
