# Generated by Django 3.2.7 on 2021-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_delete_primerinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='number_of_products_EACHONCE',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
