# Generated by Django 3.2.7 on 2021-09-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0014_setting_number_of_products_eachonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerproduct',
            name='chimerism_positions',
        ),
        migrations.RemoveField(
            model_name='primerproduct',
            name='sequence',
        ),
    ]
