# Generated by Django 3.2.7 on 2021-09-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_auto_20210922_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField(blank=True)),
                ('primer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_product', to='simulator.primerproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ChimericResultProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop1', models.IntegerField(blank=True)),
                ('stop2', models.IntegerField(blank=True)),
                ('primer_product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_product_1', to='simulator.primerproduct')),
                ('primer_product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_product_2', to='simulator.primerproduct')),
            ],
        ),
    ]
