# Generated by Django 3.2.7 on 2021-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0016_chimericresultproduct_resultproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annealedprimer',
            name='end',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='annealedprimer',
            name='start',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chimericresultproduct',
            name='stop1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chimericresultproduct',
            name='stop2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primer',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='primer',
            name='direction',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='resultproduct',
            name='stop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number_of_products_EACHONCE',
            field=models.BooleanField(),
        ),
    ]
