# Generated by Django 3.2.7 on 2021-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20210923_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultproduct',
            name='direction',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annealedprimer',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='annealedprimer',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primer',
            name='direction',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='mismatch_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='primer',
            name='sequence',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chimerism_model',
            field=models.CharField(choices=[('A', 'model A'), ('B', 'model B'), ('C', 'model C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='chimerism_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='global_termination_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='local_termination_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number_of_products',
            field=models.IntegerField(),
        ),
    ]
