# Generated by Django 3.2.7 on 2021-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_auto_20210923_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='direction',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='resultproduct',
            name='direction',
            field=models.BooleanField(),
        ),
    ]
