# Generated by Django 3.2.7 on 2021-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0019_auto_20210923_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='chimerism_model',
            field=models.CharField(choices=[('none', ''), ('A', 'model A'), ('B', 'model B'), ('C', 'model C')], max_length=10),
        ),
    ]
