# Generated by Django 3.2.7 on 2021-09-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_alter_setting_chimerism_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chimericresultproduct',
            old_name='stop1',
            new_name='stop_1',
        ),
        migrations.RenameField(
            model_name='chimericresultproduct',
            old_name='stop2',
            new_name='stop_2',
        ),
    ]
