# Generated by Django 3.2.7 on 2021-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_auto_20210923_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_string', models.CharField(max_length=1000)),
            ],
        ),
    ]
